ALTER TABLE event_templates
ADD COLUMN IF NOT EXISTS audio_url TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS audio_key TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS audio_title VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS audio_autoplay BOOLEAN NOT NULL DEFAULT FALSE;
