ALTER TABLE event_templates
ADD COLUMN IF NOT EXISTS schedule_title TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS schedule_headers TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS schedule_rows TEXT NOT NULL DEFAULT '';
